apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrators-backend
  labels:
    app: orchestrators-backend
  namespace: namespace-workflow-1699043398582
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrators-backend
  template:
    metadata:
      labels:
        app: orchestrators-backend
    spec:
      containers:
        - name: orchestrators-backend
          image: secretregistry.azurecr.io/image-workflow-1699043398582:latest
          ports:
            - containerPort: 5001