apiVersion: v1
kind: Service
metadata:
  name: orchestrators-backend
  namespace: namespace-workflow-1699043398582
spec:
  type: LoadBalancer
  selector:
    app: orchestrators-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001