apiVersion: v1
kind: Service
metadata:
  name: test-auth
  namespace: namespace-workflow-1699033509574
spec:
  type: LoadBalancer
  selector:
    app: test-auth
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001