on: push


jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

      - uses: Azure/k8s-deploy@v4
          with:
            resource-group: yourResourceGroup
            name: yourClusterName
            action: deploy
            strategy: basic

            private-cluster: true
            manifests: |
                manifests/azure-vote-backend-deployment.yaml
                manifests/azure-vote-backend-service.yaml
                manifests/azure-vote-frontend-deployment.yaml
                manifests/azure-vote-frontend-service.yaml
            images: |
                registry.azurecr.io/containername    
    