on: push


jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  deploy-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v1
        with:
          resource-group: hackWithAKS
          name: ultimateAKS
          action: deploy
          strategy: basic
          private-cluster: true
          manifests: |
            Deployment.yaml
          images: |
            secretregistry.azurecr.io/backend:backend-v0.0.3
    